name: Release

on:
  push:
    tags:
      - '*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      # - name: Run test suite
      #   run: composer run-script test
      # cp -r dt-journeys.php includes languages spinner.svg version-control.json LICENSE SECURITY.md dt-journeys/
      # Below borrowed from https://github.com/actions/upload-release-asset
      - name: Build project
        run: |
          mkdir dt-journeys
          cp -r dt-journeys.php admin charts languages magic-link post-type rest-api site-link tile workflows spinner.svg version-control.json LICENSE SECURITY.md dt-journeys/
          zip -r dt-journeys.zip dt-journeys
      - name: Create Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./dt-journeys.zip
